language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-test
dist: trusty
sudo: true
before_install:
  - sudo apt-get install gfortran
  - provision/travis/installCEA.sh
  - source /etc/profile.d/cea.sh
install:
  - provision/travis/install.sh
  - pip install -r provision/travis/requirements.txt
script: provision/travis/run-tests.sh
after_success:
  - coveralls
